apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{ .Values.app.containerPort }}
  selector:
    app: {{ .Values.app.name }}
