# Based on:
#   https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
# Grafana dashboards:
#   https://grafana.com/grafana/dashboards/9614
#   https://grafana.com/grafana/dashboards/10187
rbac:
  create: true
controller:
  ingressClass: nginx
  service:
    omitClusterIP: true
    externalTrafficPolicy: Local
  publishService:
    enabled: true
  config:
    log-format-upstream: '{"@timestamp":"$time_iso8601","host":"$hostname","server_ip":"$server_addr","client_ip":"$remote_addr","xff":"$http_x_forwarded_for","domain":"$host","url":"$request_uri","referer":"$http_referer","args":"$args","upstreamtime":"$upstream_response_time","responsetime":"$request_time","request_method":"$request_method","status":"$status","size":"$body_bytes_sent","request_body":"request_body_disable","request_length":"$request_length","protocol":"$server_protocol","upstreamhost":"$upstream_addr","file_dir":"$request_filename","http_user_agent":"$http_user_agent"}'

defaultBackend:
  enabled: false
  service:
    omitClusterIP: true  
