apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    service: {{ .Values.service.label }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    service: {{ .Values.service.label }}
